[WIP] Enable testing for denom metadata creation with erc20 hook
dymensionxyz/dymension-rdk pull request #343
Opened 2024-03-22 11:50 UTC by zale144

Add missing things to test app, refactor a bit, expand test to include erc20 hook for token creation

# PR Standards

## Opening a pull request should be able to meet the following requirements

---

Closes #311 

**All** items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow-up issues.

For Author:

- [ ]  Targeted PR against correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to Github issue with discussion and accepted design
- [ ]  Targets only one github issue
- [ ]  Wrote unit and integration tests
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)

---

For Reviewer:

- [ ]  confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  confirmed all author checklist items have been addressed

---

After reviewer approval:

- [ ]  In case targets main branch, PR should be squashed and merged.
- [ ]  In case PR targets a release branch, PR should be rebased.

2024-03-22 16:30 UTC, danwt requested changes

2024-03-22 23:00 UTC, zale144 commented on testutil/app/app.go
> +
Most of these pieces of code were copied from the app in rollapp-evm. My idea is to have the testing app as similar to the real thing as possible

2024-03-22 23:01 UTC, zale144 commented on testutil/app/app.go
> +	sdk.DefaultPowerReduction = ethermint.PowerReduction
Got it. Again, just copy pasta

2024-03-22 23:01 UTC, zale144 commented on testutil/app/app.go
> +	claimstypes.DefaultEnableClaims = false
I wish I knew myself

2024-03-24 07:10 UTC, mtsitrin commented
@zale144 
the ERC20 tests should be on the `evmos` repo
this repo is for vanilla rollapp (i.e `rollappd`)
no need to wire the evmos modules in the `app.go`

to test the `denommetadata` hooks, u should use mock callback to test it called.

2024-03-26 07:59 UTC, mtsitrin commented on x/denommetadata/keeper/msg_server_test.go
> +type mockERC20Hook struct {
next time u can use `mockery` which generates the mocks and provides assertion interface
instead of custom mock struct

2024-03-26 08:00 UTC, mtsitrin approved these changes

2024-03-26 13:31 UTC, danwt approved these changes
nice

2024-03-26 13:43 UTC, merged