feat: set denom trace while create denom metadata
dymensionxyz/dymension-rdk pull request #384
Opened 2024-04-17 08:01 UTC by trinitys7

# PR Standards

Closes #382

2024-04-17 14:13 UTC, danwt submitted a review, later dismissed

2024-04-17 16:04 UTC, omritoptix requested changes
@trinitys7 seems like the denom trace is gonna get generated also for non ibc denom. I suggest deducing it automatically by checking if the `base` starts with `IBC/`

2024-04-18 10:18 UTC, trinitys7 commented
@omritoptix The denom without IBC will have denom path is "", so I do checked it [here](https://github.com/dymensionxyz/dymension-rdk/blob/8438f45d21b680b28d7bef7efc762a48b7de614c/x/denommetadata/client/cli/tx.go#L73)

2024-04-18 12:28 UTC, trinitys7 commented
@omritoptix I set a checking path [here](https://github.com/dymensionxyz/dymension-rdk/blob/a0fae3694ce560f920063ac4449336bc0495af7d/x/denommetadata/client/cli/tx.go#L76), if the path is empty, then it's not an IBC denom

2024-04-19 10:41 UTC, omritoptix approved these changes

2024-04-19 10:42 UTC, merged