chore(contrib): Add pre push hook and script
dymensionxyz/dymension-rdk pull request #429
Opened 2024-05-23 03:59 UTC by hoangdv2429

# PR Standards

## Opening a pull request should be able to meet the following requirements

---

Closes #XXX

**All** items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow-up issues.

For Author:

- [ ]  Targeted PR against correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to Github issue with discussion and accepted design
- [ ]  Targets only one github issue
- [ ]  Wrote unit and integration tests
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)

---

For Reviewer:

- [ ]  confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  confirmed all author checklist items have been addressed

---

After reviewer approval:

- [ ]  In case targets main branch, PR should be squashed and merged.
- [ ]  In case PR targets a release branch, PR should be rebased.

2024-05-27 06:54 UTC, mtsitrin commented on contrib/githooks/pre-push
@hoangdv2429 why an empty file?

2024-05-28 09:19 UTC, danwt requested changes
what are the hooks?

https://pre-commit.com/

what's the use case?

2024-07-17 16:11 UTC, omritoptix submitted a review, later dismissed

2024-07-22 14:31 UTC, danwt commented
@hoangdv2429 ?
https://github.com/dymensionxyz/dymension-rdk/pull/429#pullrequestreview-2082223497

2024-07-24 06:39 UTC, hoangdv2429 commented
> @hoangdv2429 ? [#429 (review)](https://github.com/dymensionxyz/dymension-rdk/pull/429#pullrequestreview-2082223497)

Sorry, this script was for running golanglint and markdownlint before the push go through. Save time for additional CI run on pushing new commit.

2024-07-24 06:40 UTC, hoangdv2429 commented on contrib/githooks/pre-push
I updated it

2024-07-24 09:05 UTC, mtsitrin approved these changes

2024-07-24 10:19 UTC, artemijspavlovs commented
I would highly prefer if we could use common tooling for enforcing code quality and standards across all of dymension's repos and would urge us to use [pre-commit](https://pre-commit.com/) as pointed out by @danwt .

an example for golangci-lint is available in [roller](https://github.com/dymensionxyz/roller/blob/main/.pre-commit-config.yaml#L11-L14)

2024-07-24 10:29 UTC, hoangdv2429 commented
> I would highly prefer if we could use common tooling for enforcing code quality and standards across all of dymension's repos and would urge us to use [pre-commit](https://pre-commit.com/) as pointed out by @danwt .
> 
> an example for golangci-lint is available in [roller](https://github.com/dymensionxyz/roller/blob/main/.pre-commit-config.yaml#L11-L14)

As I read the config on roller, commit messages would be enforced to have one of those prefixes. Is this really what we need? I thought we would squash and merge PRs with the PR title as the commit message.

2024-07-24 11:11 UTC, artemijspavlovs commented
> As I read the config on roller, commit messages would be enforced to have one of those prefixes. Is this really what we need? I thought we would squash and merge PRs with the PR title as the commit message.

i was referencing just the golangci lint :)

2024-08-01 06:54 UTC, hoangdv2429 commented
I check again and see that @mtsitrin already added pre-commit to rdk. If we don't need pre-push then I think we can close it.

2024-08-01 06:54 UTC, closed without merging