feat(denommetadata): inject denom metadata to ibc transfers from RA to Hub
dymensionxyz/dymension-rdk pull request #455
Opened 2024-06-18 18:44 UTC by zale144

# PR Standards

## Opening a pull request should be able to meet the following requirements

---

Closes #454 

**All** items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow-up issues.

For Author:

- [ ]  Targeted PR against correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to Github issue with discussion and accepted design
- [ ]  Targets only one github issue
- [ ]  Wrote unit and integration tests
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)

---

For Reviewer:

- [ ]  confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  confirmed all author checklist items have been addressed

---

After reviewer approval:

- [ ]  In case targets main branch, PR should be squashed and merged.
- [ ]  In case PR targets a release branch, PR should be rebased.

2024-06-21 14:02 UTC, danwt requested changes
Makes sense I think just a couple things

Not sure about active/inactive as names. Can you think of alternatives? And they need to be documented exactly what each one means.

Also, with errors. Please prefer https://pkg.go.dev/github.com/dymensionxyz/gerr-cosmos@v0.1.2/gerrc#pkg-variables now. For example, you can wrap the AlreadyExists one there, instead of defining new ones

Also, please don't call the types. 'middleware' because they don't implement porrtypes middleware. Call them IBCModule or ICS4Wrapper

Final point: please don't implement some kind of canonical channel right now. You should write your code to assume that this is handled by some other component, and we will make an issue to fix that properly

2024-06-21 14:02 UTC, danwt commented on x/hub/keeper/keeper.go
> +	})
not really correct because how do you know this is the hub?
and why are you resetting denoms to nil?

2024-06-21 14:02 UTC, danwt commented on x/hub/keeper/keeper.go
> +	}
there is no such thing as genesis event anymore

2024-06-25 11:06 UTC, danwt requested changes
I'm not sure I'm on board with this architecturally.

I think the denom meta data module should just assume there is one hub and keep track of the registered denoms for it by itself

No need for hub keeper

2024-06-25 11:06 UTC, danwt commented on x/hub/keeper/keeper.go
> +}
not sure why hub has a id
There will surely only ever be one

2024-06-25 11:06 UTC, danwt commented on x/hub/keeper/keeper.go
> +}
please favour our shared utils package now for stuff like this
https://github.com/dymensionxyz/sdk-utils/blob/68179fdc62bb54adb05654ee6b9d1ede4bc1b672/utils/uibc/funcs.go#L28-L49
It's already used in both the hub and rdk on main branches

2024-06-25 11:06 UTC, danwt commented on proto/hub/hub.proto
> +
not needed right

2024-06-25 11:11 UTC, zale144 commented
> I'm not sure I'm on board with this architecturally.
> 
> I think the denom meta data module should just assume there is one hub and keep track of the registered denoms for it by itself
> 
> No need for hub keeper

`keep track of the registered denoms for it by itself` 
so how do we prevent the rollapp from sending the denom metadata then?

I think I already addressed a similar comment you posted: even though the hub can always be the same, technically it is still possible the hub chain can do a fork, which I believe would make it's chain ID change.

See: https://github.com/dymensionxyz/dymension-rdk/issues/465

2024-06-25 11:16 UTC, danwt commented
>so how do we prevent the rollapp from sending the denom metadata then?
WDYM?
I'm just saying to store what you currently store on the hub module in the denom meta module

Re https://github.com/dymensionxyz/dymension-rdk/issues/465 ok maybe. IDK tbh I would have to research. Seems like a delicate thing. Can you just write this PR so that it assumes that problem is solved by another component. Otherwise you're solving too many problems at once and stuff is likely to get reworked/changed anyways

Basically just write your code to have minimal assumptions so that the rest of the codebase can evolve around it independently. Here you're placing quite a lot of assumptions on the management of the hub wrt. forks etc, which is out of scope.

2024-06-25 16:18 UTC, danwt approved these changes
great work!

2024-06-25 18:03 UTC, mtsitrin approved these changes

2024-06-25 18:03 UTC, merged