feat(sequencers): added MsgUpsertSequencer
dymensionxyz/dymension-rdk pull request #568
Opened 2024-10-04 17:23 UTC by keruch

## Description

----

ADR link https://www.notion.so/dymension/ADR-x-Sequencer-Reward-Address-On-Rollapp-da84af6888c141d0a4c1a8df256a5025
Closes https://github.com/dymensionxyz/dymension/issues/1248

**All** items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow-up issues.

PR review checkboxes:

I have...

- [ ]  Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ]  Targeted PR against the correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to the GitHub issue with discussion and accepted design
- [ ]  Targets only one GitHub issue
- [ ]  Wrote unit and integration tests
- [ ]  Wrote relevant migration scripts if necessary
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)
- [ ]  Add an issue in the [e2e-tests repo](https://github.com/dymensionxyz/e2e-tests) if necessary

SDK Checklist
- [ ] Import/Export Genesis
- [ ] Registered Invariants
- [ ] Registered Events
- [ ] Updated openapi.yaml
- [ ] No usage of go `map`
- [ ] No usage of `time.Now()`
- [ ] Used fixed point arithmetic and not float arithmetic
- [ ] Avoid panicking in Begin/End block as much as possible
- [ ] No unexpected math Overflow
- [ ] Used `sendCoin` and not `SendCoins`
- [ ] Out-of-block compute is bounded
- [ ] No serialized ID at the end of store keys
- [ ] UInt to byte conversion should use BigEndian

Full security checklist [here](https://www.faulttolerant.xyz/2024-01-16-cosmos-security-1/)

----

For Reviewer:

- [ ]  Confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  Confirmed all author checklist items have been addressed

----

After reviewer approval:

- [ ]  In case the PR targets the main branch, PR should not be squash merge in order to keep meaningful git history.
- [ ]  In case the PR targets a release branch, PR must be rebased.

2024-10-07 10:55 UTC, danwt commented
build fail

2024-10-09 21:11 UTC, zale144 requested changes

2024-10-10 12:25 UTC, mtsitrin requested changes

2024-10-10 12:25 UTC, mtsitrin commented on utils/uevent/events.go
> +// TODO: import sdk-utils directly when the RDK is updated to SDK v0.47 and further.
we have sdk-util's branch dedicated for the RDK (based on v0.46)

2024-10-10 12:25 UTC, mtsitrin commented on x/sequencers/keeper/msg_server.go
> +	m.SetSequencer(ctx, v)
validate it's not already exists?

2024-10-10 12:25 UTC, mtsitrin commented on proto/sequencers/tx.proto
>      rpc CreateSequencer(MsgCreateSequencer) returns (MsgCreateSequencerResponse);
`CreateSequencer` should be removed if there's no use case for it

2024-10-10 12:25 UTC, mtsitrin commented on x/sequencers/types/helpers.go
> +func Bech32ToAddr[T sdk.AccAddress | sdk.ValAddress](addr string) (T, error) {
move to `utils/addressutils`

2024-10-11 13:05 UTC, zale144 commented on utils/addressutils/utils.go
> +func Bech32ToAddr[T sdk.AccAddress | sdk.ValAddress](addr string) (T, error) {
this could maybe be in the `sdk-utils` repo

2024-10-11 13:08 UTC, zale144 commented on utils/addressutils/utils.go
> +func Bech32ToAddr[T sdk.AccAddress | sdk.ValAddress](addr string) (T, error) {
just saw your comment and copied code below. I agree, we should first migrate to v0.47

2024-10-11 13:09 UTC, zale144 approved these changes
lgtm

2024-10-12 10:44 UTC, omritoptix reviewed
is `CreateSequencer` still needed? seems to me it can cause a situation where an operator basically can cause a collision as he may create a sequencer using connecting an already existing consensusAddr to a different bech32 address (vs the default settlement address).

2024-10-13 06:47 UTC, mtsitrin approved these changes

2024-10-13 06:56 UTC, merged